Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provision "shell", path: "server-provision.sh", run: "always"
  end

  config.vm.define "client", primary: true do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.provision "shell", path: "client-provision.sh"
    client.vm.provision "shell", path: "client-cert-setup.sh", privileged: false, run: "always"
  end
end

