pipeline {
    agent { label 'maven-agent25' }
    tools { maven 'Maven3' }
    
    stages {
        stage('Build All') {
            parallel {
                stage('Build Hello World') {
                    steps {
                        dir('lesson26/hello-world') {
                            sh 'mvn clean compile'
                        }
                    }
                }
                stage('Build Hello Jenkins') {
                    steps {
                        dir('lesson26/hello-jenkins') {
                            sh 'mvn clean compile'
                        }
                    }
                }
                stage('Build Hello DevOps') {
                    steps {
                        dir('lesson26/hello-devops') {
                            sh 'mvn clean compile'
                        }
                    }
                }
            }
        }
        
        stage('Test All') {
            parallel {
                stage('Test Hello World') {
                    steps {
                        dir('lesson26/hello-world') {
                            sh 'mvn test'
                        }
                    }
                }
                stage('Test Hello Jenkins') {
                    steps {
                        dir('lesson26/hello-jenkins') {
                            sh 'mvn test'
                        }
                    }
                }
                stage('Test Hello DevOps') {
                    steps {
                        dir('lesson26/hello-devops') {
                            sh 'mvn test'
                        }
                    }
                }
            }
        }
        
        stage('SonarQube Analysis') {
            parallel {
                stage('Hello World Analysis') {
                    steps {
                        dir('lesson26/hello-world') {
                            withSonarQubeEnv(installationName: 'SonarQube', credentialsId: 'sonar') {
                                sh '''
                                    mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
                                      -Dsonar.projectKey=lesson27-hello-world \
                                      -Dsonar.projectName="Hello World" \
                                      -Dsonar.host.url=http://192.168.1.14:9000
                                '''
                            }
                        }
                    }
                }
                stage('Hello Jenkins Analysis') {
                    steps {
                        dir('lesson26/hello-jenkins') {
                            withSonarQubeEnv(installationName: 'SonarQube', credentialsId: 'sonar') {
                                sh '''
                                    mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
                                      -Dsonar.projectKey=lesson27-hello-jenkins \
                                      -Dsonar.projectName="Hello Jenkins" \
                                      -Dsonar.host.url=http://192.168.1.14:9000
                                '''
                            }
                        }
                    }
                }
                stage('Hello DevOps Analysis') {
                    steps {
                        dir('lesson26/hello-devops') {
                            withSonarQubeEnv(installationName: 'SonarQube', credentialsId: 'sonar') {
                                sh '''
                                    mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
                                      -Dsonar.projectKey=lesson27-hello-devops \
                                      -Dsonar.projectName="Hello DevOps" \
                                      -Dsonar.host.url=http://192.168.1.14:9000
                                '''
                            }
                        }
                    }
                }
            }
        }
        
        stage('Wait for Processing') {
            steps {
                echo "Waiting 60 seconds for SonarQube to process all analyses..."
                sleep(time: 60, unit: 'SECONDS')
            }
        }
        
        stage('Check Quality Gates') {
            steps {
                script {
                    // Проверяем Quality Gates последовательно для каждого проекта
                    echo "Checking Quality Gate for Hello World..."
                    dir('lesson26/hello-world') {
                        timeout(time: 3, unit: 'MINUTES') {
                            waitForQualityGate abortPipeline: true
                        }
                    }
                    
                    echo "Checking Quality Gate for Hello Jenkins..."
                    dir('lesson26/hello-jenkins') {
                        timeout(time: 3, unit: 'MINUTES') {
                            waitForQualityGate abortPipeline: true
                        }
                    }
                    
                    echo "Checking Quality Gate for Hello DevOps..."
                    dir('lesson26/hello-devops') {
                        timeout(time: 3, unit: 'MINUTES') {
                            waitForQualityGate abortPipeline: true
                        }
                    }
                }
            }
        }
        
        stage('Package All') {
            steps {
                parallel(
                    'hello-world': {
                        sh 'mvn clean package -f lesson26/hello-world/pom.xml -DskipTests'
                    },
                    'hello-jenkins': {
                        sh 'mvn clean package -f lesson26/hello-jenkins/pom.xml -DskipTests'
                    },
                    'hello-devops': {
                        sh 'mvn clean package -f lesson26/hello-devops/pom.xml -DskipTests'
                    }
                )
            }
        }
    }
    
    post {
        always {
            // Собираем JUnit отчеты из ВСЕХ проектов
            junit 'lesson26/hello-*/target/surefire-reports/*.xml'
            
            // Архивируем артефакты
            archiveArtifacts artifacts: 'lesson26/*/target/*.jar', allowEmptyArchive: true
        }
        success { 
            echo 'lesson27 BUILD SUCCESS! All Quality Gates PASSED!' 
        }
        failure { 
            echo 'BUILD FAILED! Check logs for details.' 
        }
        aborted {
            echo 'BUILD ABORTED!'
        }
    }
}