Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    ubuntu.vm.hostname = "ubuntu"
  end
  
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/stream9"
    centos.vm.network "private_network", ip: "192.168.56.11"
    centos.vm.hostname = "centos"
  end
end
