pipeline {
    agent { label 'maven-agent25' }
    tools { maven 'Maven3' }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'pwd && ls -la lesson26/'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn clean package -f lesson26/hello-world/pom.xml'
                sh 'mvn clean package -f lesson26/hello-jenkins/pom.xml'
                sh 'mvn clean package -f lesson26/hello-devops/pom.xml'
            }
        }
        stage('Maven Test') {
            steps {
                sh 'mvn test -f lesson26/hello-world/pom.xml'
            }
        }
    }
    post {
        always {
            junit 'lesson26/hello-world/target/surefire-reports/*.xml'
            archiveArtifacts artifacts: 'lesson26/*/target/*.jar', allowEmptyArchive: true
        }
        success {
            echo 'lesson26 BUILD SUCCESS!'
        }
    }
}