apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lesson.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ include "lesson.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mysql
    spec:
      containers:
      - name: mysql
        image: "mysql:8.4"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "lesson.fullname" . }}-mysql-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wpuser"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "lesson.fullname" . }}-mysql-secrets
              key: mysql-password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi
