apiVersion: v1
kind: Service
metadata:
  name: {{ include "lesson.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  clusterIP: None
  selector:
    app.kubernetes.io/component: mysql
