apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lesson.fullname" . }}-mysql-networkpolicy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: wordpress
    ports:
    - protocol: TCP
      port: 3306
      name: mysql
