apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lesson.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
