{
 "title": "Reddit App Monitoring",
 "description": "Dashboard for Reddit App Monitoring",
 "tags": [
  "reddit",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests to UI (rate)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ui_request_count{path=\"/\"}[5m]))",
     "legendFormat": "Requests to /"
    },
    {
     "expr": "sum(rate(ui_request_count{path=\"/new\"}[5m]))",
     "legendFormat": "Requests to /new"
    }
   ]
  },
  {
   "title": "Request Traffic to UI Paths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ui_request_count{path=\"/\"}[5m])",
     "legendFormat": "{{instance}} /"
    },
    {
     "expr": "rate(ui_request_count{path=\"/new\"}[5m])",
     "legendFormat": "{{instance}} /new"
    }
   ]
  },
  {
   "title": "90th Percentile of UI Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(ui_request_response_time_bucket{path=\"/\"}[5m]))",
     "legendFormat": "90th percentile /"
    },
    {
     "expr": "histogram_quantile(0.90, rate(ui_request_response_time_bucket{path=\"/new\"}[5m]))",
     "legendFormat": "90th percentile /new"
    }
   ]
  }
 ]
}